### ISSUE TITLE
Error: package does not compile on unity Versions before 2020.3.16

### ISSUE THREAD

**Issue by Ryantheinventor** [Ryantheinventor/2DTiledMapGenerator#1]
Error: Assets/MapGenerator/Editor/RoomTileMapWindow.cs(240,27): error CS0117: 'AssetDatabase' does not contain a definition for 'SaveAssetIfDirty'
